version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: mongo_cc
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  backend:
    build: ./packages/backend
    container_name: backend_cc
    ports:
      - "4000:4000"
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/creatorcircles?authSource=admin
      NODE_ENV: development
    depends_on:
      - mongo
    volumes:
      - ./packages/backend:/app
  frontend:
    build: ./packages/frontend
    container_name: frontend_cc
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - backend
    volumes:
      - ./packages/frontend:/app
volumes:
  mongo_data:
